#!/bin/bash
#SBATCH --job-name=create-fcc    # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --time=05:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mem-per-cpu=24000

module purge
module load GCC/10.3.0  OpenMPI/4.1.1
module load  GDAL/3.3.0

./preprocess.sh 2012 2020 /home/shared/dssg23-deforestation/create_jnr-input_mapbiomass/defor-masks /home/shared/dssg23-deforestation/create_jnr-input_mapbiomass/final_maps
./create_fcc.sh /home/shared/dssg23-deforestation/create_jnr-input_mapbiomass/final_maps/forest-loss-year_map_12-20.tif /home/shared/dssg23-deforestation/create_jnr-input_mapbiomass/forest-cover/merged_map_forest-cover_2019.tif 2013 2015 2018 /home/shared/dssg23-deforestation/create_jnr-input_mapbiomass/final_maps