#!/bin/bash

# SLURM settings
JOB_NAME="stack-layers"
NODES=1
NTASKS=48
MEM_PER_CPU=3700
RUN_TIME="48:00:00"

# Paths and parameters
WORK_DIR="/home/shared/dssg23-deforestation/mapbiomas-deforest/standartization_pipeline"
PYTHON_ENV="/home/wbs/csuqqj/myenv/bin/activate"
FILES=(  
 "Test_Data/Dynamic/y/2018/cut.tif"
 "Test_Data/Dynamic/y/2019/cut.tif"
 "Test_Data/Dynamic/y/2020/cut.tif"
)

OUTPUT_VRT="merge_vrt_ytest/output.vrt"
OUTPUT_GEOTIFF="y_test_datacube.tif"
RESOLUTION="30 30"

# Modules to load
MODULES=("GCCcore/11.3.0" "Python/3.10.4" "GCC/11.3.0 OpenMPI/4.1.4" "GDAL/3.5.0" "parallel/20220722")

# Submit to SLURM
#SBATCH --job-name=$JOB_NAME
#SBATCH --nodes=$NODES
#SBATCH --ntasks-per-node=$NTASKS
#SBATCH --mem-per-cpu=$MEM_PER_CPU
#SBATCH --time=$RUN_TIME

# Set the working directory 
cd $WORK_DIR

# Activate Python Environment
source $PYTHON_ENV

# Purge all loaded modules
module purge

# Load necessary modules
for module in "${MODULES[@]}"; do
    module load $module
done

# Print start date and time
echo "Job started on `hostname` at `date`"

# Build a VRT file
gdalbuildvrt -separate $OUTPUT_VRT "${FILES[@]}" -tr $RESOLUTION

# Convert the VRT to a GeoTIFF
gdal_translate -ot float32 -of GTiff -co "BIGTIFF=YES" $OUTPUT_VRT $OUTPUT_GEOTIFF

# Print end date and time
echo "Job ended on `hostname` at `date`"
